do
  local nixvim_options = {
    autoindent = true,
    backspace = "indent,eol,start",
    backup = false,
    breakindent = true,
    clipboard = "unnamedplus",
    cmdheight = 1,
    completeopt = "menuone,noselect",
    conceallevel = 0,
    cursorcolumn = false,
    cursorline = false,
    expandtab = true,
    fileencoding = "utf-8",
    fillchars = {
      eob = " ",
      fold = "─",
      foldclose = "▸",
      foldinner = " ",
      foldopen = "▾",
      foldsep = "│",
      horiz = "─",
      horizdown = "│",
      horizup = "│",
      verthoriz = "│",
      vertleft = "│",
      vertright = "│",
      wbr = "─",
    },
    foldcolumn = "auto",
    foldenable = true,
    foldlevel = 99,
    foldlevelstart = 99,
    guicursor = "",
    hlsearch = false,
    ignorecase = true,
    incsearch = true,
    laststatus = 0,
    linebreak = true,
    mouse = "a",
    number = true,
    numberwidth = 4,
    pumheight = 10,
    relativenumber = true,
    scrolloff = 10,
    shiftwidth = 4,
    showmode = false,
    showtabline = 0,
    sidescrolloff = 8,
    signcolumn = "yes",
    smartcase = true,
    smartindent = false,
    softtabstop = 4,
    splitbelow = true,
    splitright = true,
    swapfile = false,
    tabstop = 4,
    termguicolors = true,
    timeoutlen = 300,
    undofile = true,
    updatetime = 50,
    whichwrap = "bs<>[]hl",
    wrap = false,
    writebackup = false,
  }

  for k, v in pairs(nixvim_options) do
    vim.opt[k] = v
  end
end
