require("core.keymaps")
require("core.opts")
require("core.colorscheme")

require("plugins.oil")
require("plugins.alpla")
require("plugins.comment")
require("plugins.harpoon")
require("plugins.telescope")
require("plugins.which-key")
require("plugins.lualine")
require("plugins.misc")
require("plugins.notify")
require("plugins.git")
