require("core.colorscheme")
require("core.keymaps")
require("core.opts")
require("core.autocommand")
require("core.diagnostics")

require("plugins.treesitter")
require("plugins.lualine")
require("plugins.telescope")

require("plugins.lspsaga")
require("plugins.null-ls")
require("plugins.blink-cmp")
require("plugins.lsp")

require("plugins.oil")
require("plugins.alpla")
require("plugins.comment")
require("plugins.harpoon")
require("plugins.which-key")
require("plugins.misc")
require("plugins.git")
require("plugins.ufo")

-- require("plugins.cmp")
-- require("plugins.noice")
-- require("plugins.notify")
-- require("utils.term")
-- require("utils.jutsu")
