require("nvim-surround").setup({})
require("nvim-autopairs").setup({})
require("todo-comments").setup({ signs = true })
require("colorizer").setup({})
require("cord").setup({ display = { show_time = true } })
